-- 비빌번호(0000): $2a$10$5rAh.EQrYqeqBQYOf.RYH.KsmfyYo8jYMV1jsTSNaTG.ymklzUKMO

INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_CODE.NEXTVAL, '관리자', 'admin', '$2a$10$5rAh.EQrYqeqBQYOf.RYH.KsmfyYo8jYMV1jsTSNaTG.ymklzUKMO', 'ohgiraffers@gmail.com');
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_CODE.NEXTVAL, '테스터', 'test01', '$2a$10$5rAh.EQrYqeqBQYOf.RYH.KsmfyYo8jYMV1jsTSNaTG.ymklzUKMO', 'test01@naver.com');

INSERT INTO TBL_AUTHORITY VALUES (SEQ_AUTHORITY_CODE.NEXTVAL, 'ROLE_ADMIN', '관리자');
INSERT INTO TBL_AUTHORITY VALUES (SEQ_AUTHORITY_CODE.NEXTVAL, 'ROLE_USER', '일반회원');

INSERT INTO TBL_MEMBER_ROLE VALUES (1, 1);
INSERT INTO TBL_MEMBER_ROLE VALUES (1, 2);
INSERT INTO TBL_MEMBER_ROLE VALUES (2, 2); 

INSERT INTO TBL_CATEGORY
VALUES
('1', '한식');

INSERT INTO TBL_CATEGORY
VALUES
('2', '중식');

INSERT INTO TBL_CATEGORY
VALUES
('3', '일식');

INSERT INTO TBL_CATEGORY
VALUES
('4', '양식');

INSERT INTO TBL_CATEGORY
VALUES
('5', '디저트');

INSERT INTO TBL_CATEGORY
VALUES
('6', '음료');

INSERT INTO TBL_CATEGORY
VALUES
('7', '기타');