-- 관리자 계정에서 계정 추가
-- 계정 생성 및 권한 부여(SYSTEM 계정에서 할 것)
--CREATE USER C##BBOK IDENTIFIED BY BBOK;

-- 한 줄로 권한 두개 이상을 줄 수도 있다.
--GRANT CONNECT, RESOURCE TO C##BBOK;

-- 해당 계정에서 DDL 및 DML 작업을 하기 위해 필요한 작업(SYSTEM 계정에서 할 것)
--ALTER USER C##BBOK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;    -- TABLESPACE 확보
--ALTER USER C##BBOK QUOTA 1024M ON SYSTEM;                           		  -- SYSTEM 공간 확보

DROP TABLE "TBL_MENU";

CREATE TABLE "TBL_MENU" (
	"MENU_CODE"	NUMBER		NOT NULL,
	"CATEGORY_CODE"	NUMBER		NOT NULL,
	"MENU_NAME"	VARCHAR2(255)		NOT NULL,
	"MENU_PRICE"	NUMBER		NOT NULL,
	"MENU_DESCRIPTION"	VARCHAR2(1000)		NULL,
	"MENU_ORDERABLE"	CHAR(1)		NOT NULL,
	"MENU_IMAGE"	VARCHAR2(255)		NULL,
	"MENU_STOCK"	NUMBER		NOT NULL
);

DROP TABLE "TBL_CATEGORY";

CREATE TABLE "TBL_CATEGORY" (
	"CATEGORY_CODE"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(255)		NOT NULL
);

DROP TABLE "TBL_AUTHORITY";

CREATE TABLE "TBL_AUTHORITY" (
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"AUTHORITY_NAME"	VARCHAR2(255)		NOT NULL,
	"AUTHORITY_DESC"	VARCHAR2(255)		NOT NULL
);

DROP TABLE "TBL_MEMBER";

CREATE TABLE "TBL_MEMBER" (
	"MEMBER_CODE"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(255)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(255)		NOT NULL,
	"MEMBER_PASSWORD"	VARCHAR2(255)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(255)		NOT NULL
);

DROP TABLE "TBL_MEMBER_ROLE";

CREATE TABLE "TBL_MEMBER_ROLE" (
	"AUTHORITY_CODE"	NUMBER		NOT NULL,
	"MEMBER_CODE"	NUMBER		NOT NULL
);

DROP TABLE "TBL_CART";

CREATE TABLE "TBL_CART" (
	"CART_CODE"	NUMBER		NOT NULL,
	"MENU_CODE"	NUMBER		NOT NULL,
	"AMOUNT"	NUMBER	DEFAULT 1	NOT NULL,
	"CREATE_DATE"	DATE		NOT NULL,
	"MEMBER_CODE"	NUMBER		NOT NULL
);

ALTER TABLE "TBL_MENU" ADD CONSTRAINT "PK_TBL_MENU" PRIMARY KEY (
	"MENU_CODE",
	"CATEGORY_CODE"
);

ALTER TABLE "TBL_CATEGORY" ADD CONSTRAINT "PK_TBL_CATEGORY" PRIMARY KEY (
	"CATEGORY_CODE"
);

ALTER TABLE "TBL_AUTHORITY" ADD CONSTRAINT "PK_TBL_AUTHORITY" PRIMARY KEY (
	"AUTHORITY_CODE"
);

ALTER TABLE "TBL_MEMBER" ADD CONSTRAINT "PK_TBL_MEMBER" PRIMARY KEY (
	"MEMBER_CODE"
);

ALTER TABLE "TBL_MEMBER_ROLE" ADD CONSTRAINT "PK_TBL_MEMBER_ROLE" PRIMARY KEY (
	"AUTHORITY_CODE",
	"MEMBER_CODE"
);

ALTER TABLE "TBL_CART" ADD CONSTRAINT "PK_TBL_CART" PRIMARY KEY (
	"CART_CODE",
	"MENU_CODE"
);

ALTER TABLE "TBL_MENU" ADD CONSTRAINT "FK_TBL_CATEGORY_TO_TBL_MENU_1" FOREIGN KEY (
	"CATEGORY_CODE"
)
REFERENCES "TBL_CATEGORY" (
	"CATEGORY_CODE"
);

ALTER TABLE "TBL_MEMBER_ROLE" ADD CONSTRAINT "FK_TBL_AUTHORITY_TO_TBL_MEMBER_ROLE_1" FOREIGN KEY (
	"AUTHORITY_CODE"
)
REFERENCES "TBL_AUTHORITY" (
	"AUTHORITY_CODE"
);

ALTER TABLE "TBL_MEMBER_ROLE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_MEMBER_ROLE_1" FOREIGN KEY (
	"MEMBER_CODE"
)
REFERENCES "TBL_MEMBER" (
	"MEMBER_CODE"
);

ALTER TABLE "TBL_CART" ADD CONSTRAINT "FK_TBL_MENU_TO_TBL_CART_1" FOREIGN KEY (
	"MENU_CODE"
)
REFERENCES "TBL_MENU" (
	"MENU_CODE"
);

ALTER TABLE "TBL_CART" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_CART_1" FOREIGN KEY (
	"MEMBER_CODE"
)
REFERENCES "TBL_MEMBER" (
	"MEMBER_CODE"
);



DROP SEQUENCE SEQ_MENU_CODE;
CREATE SEQUENCE SEQ_MENU_CODE
    START WITH 1
    NOCACHE;

DROP SEQUENCE SEQ_MEMBER_CODE;
CREATE SEQUENCE SEQ_MEMBER_CODE
    START WITH 1
    NOCACHE;

DROP SEQUENCE SEQ_CART_CODE;
CREATE SEQUENCE SEQ_CART_CODE
    START WITH 1
    NOCACHE;

DROP SEQUENCE SEQ_CART_CODE;
CREATE SEQUENCE SEQ_AUTHORITY_CODE
    START WITH 1
    NOCACHE;

