import {
    GET_MENU,
    GET_MENUS,
    GET_MENUS_KOREAN,
    GET_MENUS_CHINESE,
    GET_MENUS_JAPANESE,
    GET_MENUS_WESTERN,
    GET_MENUS_DESSERT,
    GET_MENUS_BEVERAGE,
    GET_MENUS_ETC
} from 